name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *' # 每小时

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CROSS_REPO_TOKEN }}
              
      - name: Configure Submodules to Track Branches
        run: |
          git submodule foreach '
            git checkout main || git checkout -b main
            git branch --set-upstream-to=origin/main main
          '
          
      - name: Update Submodules
        run: git submodule update --recursive --remote
        
      - name: Configure Git Identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Check and Compress Database Files
        run: |
          find ./assets -name '*.db' -exec gzip -9 {} \; -exec echo "已压缩： {}" \;

      - name: Commit Changes
        shell: bash
        run: |
          git submodule foreach --recursive bash -c '
            if [[ -n "$(git status --porcelain)" ]]; then
              git add .
              git commit -m "压缩子模块资源"
            fi
          '

      - name: Decompress Assets
        run: find ./assets -name '*.gz' -exec gzip -d {} \;

      - name: Update Assets
        run: |
          chmod +x update.sh
          ./update.sh
      - name: Update Submodule References
        run: |
          submodule_paths=$(git submodule status | awk '{ print $2 }')
          for submodule in $submodule_paths; do
            git add $submodule
          done
          git commit -m "更新子模块指针 [skip ci]"
          git push --recurse-submodules=on-demand origin HEAD

      - name: Cleanup
        run: find . -type d -name "temp" -exec rm -rf {} +

      - name: Upload Artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './assets'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
