name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *' # 每小时

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure Git Identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Update Submodule Remotes
        run: |
          git submodule foreach '
            current_url=$(git config --get remote.origin.url);
            new_url=$(echo "$current_url" | sed "s|https://github.com|https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com|");
            git remote set-url origin "$new_url";
          '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Check and Compress Database Files
        run: |
          find ./assets -name '*.db' -exec gzip -9 {} \; -exec echo "已压缩： {}" \;

      - name: Commit and Push Changes in Submodules
        shell: bash
        run: |
          git submodule foreach --recursive bash -c '
            if [[ -n "$(git status --porcelain)" ]]; then
              git add .
              git commit -m "压缩子模块资源 [skip ci]"
              git push
            fi
          '

      - name: Commit Submodule Reference in Parent Repo
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "更新主项目资源 [skip ci]"
            git push
          fi

      - name: Decompress Assets
        run: find ./assets -name '*.gz' -exec gzip -d {} \;

      - name: Update Assets
        run: |
          chmod +x update.sh
          ./update.sh

      - name: Cleanup
        run: find . -type d -name "temp" -exec rm -rf {} +

      - name: Upload Artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './assets'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
