name: Deploy to Cloudflare R2

on:
  workflow_dispatch:
  push:
  repository_dispatch:
    types: [run-deployment]
permissions:
  contents: write
  #pages: write
  #id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone build dependencies
        run: git clone --depth 1 https://github.com/asfu222/BlueArchiveLocalizationTools.git
      - name: Restore FlatData Cache
        uses: actions/cache@v4
        with:
          path: BlueArchiveLocalizationTools/Extracted/FlatData
          key: ${{ runner.os }}-flatdata-${{ hashFiles('ba.env') }}
          restore-keys: |
            ${{ runner.os }}-flatdata-

      - name: Download updated assets
        run: |
          chmod +x update.sh
          ./update.sh

      - name: Restore Excel Cache
        uses: actions/cache@v4
        with:
          path: |
            BlueArchiveLocalizationTools/Extracted/Table/Excel
            BlueArchiveLocalizationTools/Extracted/Temp/Table/Excel
          key: ${{ runner.os }}-excelzip-${{ hashFiles('Excel.zip') }}
          restore-keys: |
            ${{ runner.os }}-excelzip-

      - name: Configure Submodules to Track Branches
        run: |
          git submodule foreach '
            git checkout main || git checkout -b main
            git branch --set-upstream-to=origin/main main
          '
          
      - name: Update Submodules
        run: git submodule update --recursive --remote
        
      - name: Configure Git Identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      #- name: Setup GitHub Pages
      #  uses: actions/configure-pages@v5

      - name: Decompress Assets
        run: find ./assets -name '*.gz' -exec gzip -d {} \;

      - name: Build Assets
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Update Submodule References
        run: |
          submodule_paths=$(git submodule status | awk '{ print $2 }')
          for submodule in $submodule_paths; do
            git add $submodule
          done
          if git diff --cached --quiet; then
            echo "子模块已是最新状态"
          else
            git commit -m "更新子模块指针 [skip ci]"
            git push --recurse-submodules=on-demand origin HEAD
          fi

      - name: Deploy to Cloudflare R2
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT }}
          AWS_MAX_ATTEMPTS: 5
        run: aws s3 sync assets/ s3://${{ secrets.R2_BUCKET }}/ --exclude ".git" --checksum-algorithm CRC32
        
      - name: Purge Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
             -H "Authorization: Bearer ${{ secrets.CF_PURGE_TOKEN }}" \
             -H "Content-Type: application/json" \
             --data '{"purge_everything":true}'
          
      #- name: Check if should deploy
      #  id: check_deploy
      #  run: |
      #    if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
      #      echo "Manual trigger – proceeding with deployment."
      #      echo "should_deploy=true" >> $GITHUB_ENV
      #      exit 0
      #    fi
      #    PREVIOUS_DEPLOY_URL="https://bluearchive.me/.last_deployed_commit"
      #    curl -s $PREVIOUS_DEPLOY_URL > .last_deployed_commit
      #    if [ -f .last_deployed_commit ]; then
      #      LAST_DEPLOYED=$(cat .last_deployed_commit)
      #    else
      #      LAST_DEPLOYED=""
      #    fi
      #    CURRENT=$(git rev-parse HEAD)
      #    echo "Current commit: $CURRENT"
      #    echo "Last deployed commit: $LAST_DEPLOYED"
      #    if [ "$CURRENT" = "$LAST_DEPLOYED" ]; then
      #      echo "No new commit detected. Skipping deployment."
      #      echo "should_deploy=false" >> $GITHUB_ENV
      #    else
      #      echo "New commit detected. Proceeding with deployment."
      #      echo "should_deploy=true" >> $GITHUB_ENV
      #      echo $CURRENT > ./assets/.last_deployed_commit
      #    fi
          
      #- name: Upload Artifact to GitHub Pages
      #  uses: actions/upload-pages-artifact@v3
      #  if: ${{ env.should_deploy == 'true' }}
      #  with:
      #    path: './assets'

      #- name: Deploy to GitHub Pages
      #  uses: actions/deploy-pages@v4
      #  if: ${{ env.should_deploy == 'true' }}