name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Decompress assets
        run: |
          find ./assets -name '*.gz' -exec sh -c 'gzip -d "{}"' \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './assets'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
