name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # 零点北京时间

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Decompress assets
        run: |
          find ./assets -name '*.gz' -exec sh -c 'gzip -d "{}"' \;
          chmod +x update.sh
          ./update.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './assets'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
