name: Update Yostar Server URL

on:
  schedule:
    - cron: "0 9,10,15 * * *"
  workflow_dispatch:
permissions:
  contents: write
  actions: write
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Clone BlueArchiveLocalizationTools repository
        run: |
          git clone --depth 1 https://github.com/asfu222/BlueArchiveLocalizationTools.git

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r BlueArchiveLocalizationTools/requirements.txt

      - name: Run update_urls.py with ba.env
        run: |
          python BlueArchiveLocalizationTools/update_urls.py ba.env

      - name: Commit and push changes if ba.env was modified
        run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add ba.env
            git status
            if git diff --cached --quiet; then
              echo "没有检测到更新，跳过提交"
            else
              echo "检测到悠星服务器URL更新，正在更新ba.env网址..."
            
              git commit -m "更新悠星服务器URL"
              
              git push origin HEAD
              
              curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/dispatches \
                -d '{"event_type": "run-deployment"}'
            fi