name: Update Yostar Server URL

on:
  schedule:
    - cron: "0 9,10,15 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Clone BlueArchiveLocalizationTools repository
        run: |
          git clone --depth 1 https://github.com/asfu222/BlueArchiveLocalizationTools.git

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r BlueArchiveLocalizationTools/requirements.txt

      - name: Run update_urls.py with ba.env
        run: |
          python BlueArchiveLocalizationTools/update_urls.py ba.env server-info.json
      - name: Check if ba.env was modified
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ba.env
          git status
          if git diff --cached --quiet; then
            echo "没有检测到更新，跳过提交"
            echo "update_detected=false" >> $GITHUB_ENV
          else
            echo "检测到悠星服务器URL更新，正在更新ba.env网址..."
            echo "update_detected=true" >> $GITHUB_ENV
          fi
      - name: Deploy updated server json to Cloudflare R2
        if: env.update_detected == 'true'
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT }}
          AWS_MAX_ATTEMPTS: 5
        run: |
          sed -i 's|https://prod-clientpatch.bluearchiveyostar.com/|https://prod-clientpatch.bluearchive.me:6969/|g' server-info.json
          aws s3 cp server-info.json s3://${{ secrets.R2_BUCKET }}/static/server-info.json --checksum-algorithm CRC32
      - name: Purge Cloudflare Cache
        if: env.update_detected == 'true'
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
             -H "Authorization: Bearer ${{ secrets.CF_PURGE_TOKEN }}" \
             -H "Content-Type: application/json" \
             --data '{"purge_everything":true}'
      - name: Commit and push changes if ba.env was modified
        if: env.update_detected == 'true'
        run: |
          git commit -m "更新悠星服务器URL"
          git push origin HEAD
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "run-deployment"}'
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.RSS_DL_REPO_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/asfu222/BAJPDownloader/dispatches \
            -d '{"event_type": "build-apk"}'
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.COMMON_PNG_SRC }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/asfu222/commonpngsrc/dispatches \
            -d '{"event_type": "update-assets"}'
      - name: Trigger APK source update using push
        if: env.update_detected == 'true'
        env:
          TARGET_REPO_URL: https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/asfu222/BAJPApkSrc.git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git clone "$TARGET_REPO_URL" BAJPApkSrc
          date > BAJPApkSrc/.date
          cd BAJPApkSrc
          git add .date
          git commit -m "Update date"
          git push origin
